apiVersion: iam.upbound.io/v1alpha1
kind: Token
metadata:
  name: mytoken
spec:
  forProvider:
    name: mytoken
    owner:
      type: robots
      name: myuser
  writeConnectionSecretToRef:
    name: up-token
    namespace: crossplane-system