apiVersion: mcp.upbound.io/v1alpha1
kind: ControlPlanePermission
metadata:
  name: owner-team-a
spec:
  forProvider:
    organizationName: upbound
    teamIdRef:
      name: team-a
    controlPlaneNameRef:
      name: controlplane-a
    permission: owner
